imports:
  - {resource: console.php}
parameters:
  paths.sites: '%paths.project%/sites'
services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $projectPath: '%paths.project%'
      $sitesPath: '%paths.sites%'
  TJM\ShellRunner\ShellRunner: ~
  TJM\TMCom\Command\:
    resource: '%paths.project%/src/Command'
    tags: ['console.command']
  TJM\TMCom\Dev: ~
  TJM\TMCom\Sites:
    arguments:
      - '%paths.sites%'
      -
        10kgol: 10k-gol.site
        dev: dev.tobymackenzie.com
        tm: tobymackenzie.com
        priv: tmprivate
        private: tmprivate
        tmcom: tobymackenzie.com
        tmweb: tobymackenzie.com

tjm_console:
  name: 'server-tobymackenzie.com'
  version: '0.1'
