imports:
  - {resource: console.php}
parameters:
  paths.sites: '%paths.project%/sites'
services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $backupPaths: ['/Volumes/cx8']
      $projectPath: '%paths.project%'
      $siteAliases:
        10kgol: 10k-gol.site
        dev: dev.tobymackenzie.com
        tm: tobymackenzie.com
        priv: tmprivate
        private: tmprivate
        tmcom: tobymackenzie.com
        tmweb: tobymackenzie.com
      $sitesPath: '%paths.sites%'
      $servers:
        public:
          host: tobymackenzie.com
          user: 2b
        prod: public
        dev:
          env: dev
          host: deploy.t
          user: ubuntu
  TJM\ShellRunner\ShellRunner: ~
  TJM\TMCom\Command\:
    resource: '%paths.project%/src/Command'
    tags: ['console.command']
  TJM\TMCom\Dev: ~
  TJM\TMCom\Servers: ~
  TJM\TMCom\Sites: ~

tjm_console:
  name: 'server-tobymackenzie.com'
  version: '0.1'
