imports:
  - {resource: console.php}
parameters:
  paths.sites: '%paths.project%/sites'
services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $projectPath: '%paths.project%'
      $sitesPath: '%paths.sites%'
  TJM\ShellRunner\ShellRunner: ~
  TJM\TMCom\Command\:
    resource: '%paths.project%/src/Command'
    tags: ['console.command']
  TJM\TMCom\Dev: ~
    arguments: ['%paths.project%']

tjm_console:
  name: 'server-tobymackenzie.com'
  version: '0.1'
